### ISSUE TITLE
Could not get unknown property 'getJavaCompileProvider'

### ISSUE THREAD

**Issue by freddieerg** [ghondar/react-native-torrent-streamer#10]
Installed using yarn exactly as the instructions say to do so, using a compatible version of react native but get this error everytime:

`Could not get unknown property 'getJavaCompileProvider' for object of type com.android.build.gradle.internal.api.LibraryVariantImpl.
`

**Comment by ThalKod** [comment]
@freddieerg I'm having the same exact error, can you tell me how did you solve it ?

**Comment by freddieerg** [comment]
@ThalKod I think you need to roll back to 0.2.0 to use javaCompile instead of getJavaCompileProvider.
