### ISSUE TITLE
0.63 not working

### ISSUE THREAD

**Issue by krunaldodiya** [ghondar/react-native-torrent-streamer#18]
Hi, I have created new project using react native 0.63.3 and also it's functional component, i tried to integrate it but nothing works, please add support for 0.63.*

```
import React, {useEffect} from 'react';
import {Button, SafeAreaView, StatusBar, Text} from 'react-native';
import TorrentStreamer from 'react-native-torrent-streamer';

const magnet =
  'magnet:?xt=urn:btih:942c4e341488b632b49b0628b5a37716818d5269&dn=Artemis.Fowl.2020.REPACK.720p.DSNP.WEBRip.800MB.x264-GalaxyRG%5BTGx%5D&xl=835868069&tr=udp%3A%2F%2Ftracker.coppersurfer.tk:6969/announce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org:6969/announce&tr=udp%3A%2F%2Ftracker.cyberia.is:6969/announce&tr=udp%3A%2F%2Ftracker.iamhansen.xyz:2000/announce&tr=udp%3A%2F%2Fp4p.arenabg.com:1337/announce&tr=udp%3A%2F%2Fexplodie.org:6969/announce&tr=udp%3A%2F%2Ftracker.opentrackr.org:1337/announce&tr=udp%3A%2F%2Ftracker.tiny-vps.com:6969/announce&tr=udp%3A%2F%2Fexodus.desync.com:6969/announce&tr=udp%3A%2F%2Ftracker.torrent.eu.org:451/announce&tr=udp%3A%2F%2Ftracker.moeking.me:6969/announce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu:80/announce&tr=udp%3A%2F%2Fopen.stealth.si:80/announce&tr=udp%3A%2F%2F9.rarbg.to:2710/announce&tr=udp%3A%2F%2Fopentor.org:2710/announce';

const App = () => {
  useEffect(() => {
    TorrentStreamer.addEventListener('ready', (data: any) => {
      console.log(data, 'data');
    });
  }, []);

  useEffect(() => {
    TorrentStreamer.addEventListener('status', (data: any) => {
      console.log(data, 'data');
    });
  }, []);

  useEffect(() => {
    TorrentStreamer.addEventListener('error', (data: any) => {
      console.log(data, 'data');
    });
  }, []);

  useEffect(() => {
    TorrentStreamer.addEventListener('stop', (data: any) => {
      console.log(data, 'data');
    });
  }, []);

  const startTorrent = () => {
    try {
      console.log('starting');

      TorrentStreamer.start(magnet);
    } catch (error) {
      console.log('error', error);
    }
  };

  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Button title="hello" onPress={startTorrent} />
      </SafeAreaView>
    </>
  );
};

export default App;
```

**Comment by rnidea2code** [comment]
same here it is not working

**Comment by rnidea2code** [comment]
@ghondar not working
import React, {Component} from 'react';
import {StyleSheet, View, Text, TouchableHighlight} from 'react-native';

import TorrentStreamer from 'react-native-torrent-streamer';

export default class App extends Component {
  state = {
    progress: 0,
    buffer: 0,
    downloadSpeed: 0,
    seeds: 0,
  };

  componentDidMount() {
    TorrentStreamer.addEventListener('error', this.onError);
    TorrentStreamer.addEventListener('status', this.onStatus.bind(this));
    TorrentStreamer.addEventListener('ready', this.onReady.bind(this));
    TorrentStreamer.addEventListener('stop', this.onStop.bind(this));
  }

  onError(e) {
    console.log(e);
  }

  onStatus({progress, buffer, downloadSpeed, seeds}) {
    this.setState({
      progress,
      buffer,
      downloadSpeed,
      seeds,
    });
  }

  onReady(data) {
    TorrentStreamer.open(data.url, 'video/mp4');
  }

  onStop(data) {
    console.log('stop');
  }

  render() {
    const {progress, buffer, downloadSpeed, seeds} = this.state;

    return (
      <View style={styles.container}>
        <TouchableHighlight
          style={styles.button}
          onPress={this._handleStart.bind(this)}>
          <Text>Start Torrent!</Text>
        </TouchableHighlight>

        <TouchableHighlight
          style={styles.button}
          onPress={this._handleStop.bind(this)}>
          <Text>Stop Torrent!</Text>
        </TouchableHighlight>

        {buffer ? <Text>Buffer: {buffer}</Text> : null}
        {downloadSpeed ? (
          <Text>
            Download Speed: {(downloadSpeed / 1024).toFixed(2)} Kbs/seg
          </Text>
        ) : null}
        {progress ? (
          <Text>Progress: {parseFloat(progress).toFixed(2)}</Text>
        ) : null}
        {seeds ? <Text>Seeds: {seeds}</Text> : null}
      </View>
    );
  }

  _handleStart() {
    console.log('statred');
    TorrentStreamer.start(
      'magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent',
    );
  }

  _handleStop() {
    this.setState(
      {
        progress: 0,
        buffer: 0,
        downloadSpeed: 0,
        seeds: 0,
      },
      () => {
        TorrentStreamer.stop();
      },
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

**Comment by ghondar** [comment]
hello @krunaldodiya @rnidea2code, you need to grant storage permissions in the app

**Comment by rnidea2code** [comment]
@krunaldodiya  
Thanks
