### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by Ouri028** [ghondar/react-native-torrent-streamer#20]
Hi,

I discovered that on Android 10, when clicking the start button nothing happens, but when changing the emulator to Android 9 all works fine.

Storage Permission has been granted on both emulators and no errors get logged when testing.

@ghondar Will it be possible to add Android 10+ support?

**Comment by ghondar** [comment]
hi @Ouri028 on Android 10, you need change sdk version and activate the  requestLegacyEsternalStorage like this
![](https://user-images.githubusercontent.com/6628637/108601776-55ea1b00-736c-11eb-8e70-380d9d73e58f.png)

**Comment by Ouri028** [comment]
Thanks @ghondar , I'll give it a test and will report back.

**Comment by Ouri028** [comment]
Working like a charm, thanks again!
