### ISSUE TITLE
Cant get it to run 

### ISSUE THREAD

**Issue by Uthpala** [ghondar/react-native-torrent-streamer#3]
/Users/home/code/bingewatch/node_modules/react-native-torrent-streamer/android/torrent/src/main/java/com/ghondar/torrentstreamer/TorrentStreamerPackage.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-torrent-streamer:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-torrent-streamer:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ghondar** [comment]
fixed ```npm i -D react-native-torrent-streamer@0.0.7```

**Comment by Uthpala** [comment]
I will check and let you know. Is possible for you to make this work on IOS ?

**Comment by ghondar** [comment]
sorry but i'm not Objective-c dev

**Comment by Uthpala** [comment]
@ghondar I got it to work. But not perfectly. It downloaded a file but not all of it. Only partly plus how can we define where to store the file ? 
And is there a way to resume downloads ? 

In your Example Component do not import React and Component from 'react-native' they should be imported from 'react'

**Comment by ghondar** [comment]
@Uthpala can you share the magnet link?

**Comment by Uthpala** [comment]
@ghondar  here you go 

magnet:?xt=urn:btih:5117ba78c8e82a1d070855081b61ac2bc0743dcf&dn=The+Big+Bang+Theory+S11E02+HDTV+x264-LOL&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

**Comment by ghondar** [comment]
new version with:
- Torrent library updated
- Status event more detailed 

Please read readme.md if you want test it. btw i've tested your magnet url without problems

pd: Don't use componentWillUnmount removing listeners, if you are using TorrentStreamer.open(...) when external player is opened componentWillUnmount is fired
