### ISSUE TITLE
Update to work with react-native 0.60 and torrent streamer version 4.6.1

### ISSUE THREAD

**Issue by Rob2k9** [ghondar/react-native-torrent-streamer#8]
would it be possible to have this updated to work with the latest version of react-native and also work using version 4.6.1 of torrent streamer for android please ?

**Comment by ghondar** [comment]
hello @Rob2k9 checkout this version [0.2.0](https://github.com/ghondar/react-native-torrent-streamer/releases/tag/v0.2.0)

**Comment by Rob2k9** [comment]
Thank you setup with no issues this time with react 6.0 but i noticed when i press start using emulator nothing happens trying it on real device when i get a new one from store today dose it not work on emulator ?

**Comment by ghondar** [comment]
you need activate storage permission ![Screen](https://user-images.githubusercontent.com/6628637/63217114-a93f3580-c105-11e9-9910-8cf3ead5f778.png)

**Comment by Rob2k9** [comment]
Ahh ok i will have a look at including something like react-native-permissions into it so it automaticly requests the permission when the app opens for the first time

**Comment by ghondar** [comment]
[0.2.1](https://github.com/ghondar/react-native-torrent-streamer/releases/tag/v0.2.1) release added

**Comment by ghondar** [comment]
> Ahh ok i will have a look at including something like react-native-permissions into it so it automaticly requests the permission when the app opens for the first time

sure do you have these library
